// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EpClose: typeof import('~icons/ep/close')['default']
    EpFullScreen: typeof import('~icons/ep/full-screen')['default']
    EpLoading: typeof import('~icons/ep/loading')['default']
    EpMinus: typeof import('~icons/ep/minus')['default']
    EpPlus: typeof import('~icons/ep/plus')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
